### ISSUE TITLE
POST to leftovers broken

### ISSUE THREAD

**Issue by teleclimber** [teleclimber/Leftovers#1]
Trying to move to a more recent Deno std lib but things are broken now.

```
Error: Did not expect an array. key: image
at getUploaded (file:///Users/ollie/Documents/Code/Leftovers/app/handlers/leftovers.ts:148:36)
at async Object.postLeftoverItem [as handler] (file:///Users/ollie/Documents/Code/Leftovers/app/handlers/leftovers.ts:59:20)
at async DsRouteServer.handleRequest (file:///var/folders/6z/x6_ksh3d2blc7s6rn5fy098h0000gn/T/041328701/sandbox-code/ds-route-server.ts:130:4)
```

**Comment by teleclimber** [comment]
Can no longer reproduce. Probably fixed in abebb053aa1174419f1cbce8983e1f3fab2edd19
